server:
  assets-path: /app/assets
branding:
  hide-footer: true
  logo-url: https://cdn.discordapp.com/attachments/700991964564291624/1369235765137117226/app-icon.png?ex=681b1fad&is=6819ce2d&hm=0ccb83161594c3eb93f70344e091965f672e12dbf45755a7b9e097312b33b443&
  favicon-url: https://cdn.discordapp.com/attachments/700991964564291624/1369235765137117226/app-icon.png?ex=681b1fad&is=6819ce2d&hm=0ccb83161594c3eb93f70344e091965f672e12dbf45755a7b9e097312b33b443&

theme:
  light: false
  background-color: 200 18 3
  primary-color: 32 88 49
  positive-color: 174 84 44
  negative-color: 341 85 45
  contrast-multiplier: 1
  text-saturation-multiplier: 1.8

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
