server:
  assets-path: /app/assets
branding:
  hide-footer: true
  logo-url: <iframe src="https://drive.google.com/file/d/1j-ZQ4HwzJC_mKc3GK4szNBb_B1dJzHZa/preview" width="640" height="480" allow="autoplay"></iframe>
  favicon-url: <iframe src="https://drive.google.com/file/d/1j-ZQ4HwzJC_mKc3GK4szNBb_B1dJzHZa/preview" width="640" height="480" allow="autoplay"></iframe>

theme:
  light: false
  background-color: 200 18 3
  primary-color: 32 88 49
  positive-color: 174 84 44
  negative-color: 341 85 45
  contrast-multiplier: 1
  text-saturation-multiplier: 1.8

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
