server:
  assets-path: /app/assets
branding:
  hide-footer: true
  logo-url: <a href="https://imgbb.com/"><img src="https://i.ibb.co.com/DP3PL4xD/app-icon.png" alt="app-icon" border="0"></a>
  favicon-url: <a href="https://imgbb.com/"><img src="https://i.ibb.co.com/DP3PL4xD/app-icon.png" alt="app-icon" border="0"></a>

theme:
  light: false
  background-color: 200 18 3
  primary-color: 32 88 49
  positive-color: 174 84 44
  negative-color: 341 85 45
  contrast-multiplier: 1
  text-saturation-multiplier: 1.8

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
