
- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  head-widgets:
      - type: markets
        hide-header: true
        cache: 1m
        markets:
          - symbol: ^JKSE
            name: IHSG
          - symbol: IDR=X
            name: IDR/USD
          - symbol: JPYIDR=X
            name: JPY/IDR  
          - symbol: SGDIDR=X
            name: SGD/IDR
          - symbol: GC=F
            name: GOLD^JKSE

  columns:
    - size: small
      widgets:
        - type: custom-api
          hide-header: true
          title: Next Race
          cache: 1d
          url: https://f1api.dev/api/current/next
          template:
            <div class="flex flex-column gap-5">
              {{ $session := index (.JSON.Array "race") 0 }}
              <p class="size-h5">
                Round {{ .JSON.String "round" }}
              </p>

              <div class="margin-block-4">
                <p class="color-highlight">{{ $session.String "raceName" }}</p>
                <p class="color-primary">
                  <span>Race</span>
                </p>
                <p class="size-h5">{{ $session.String "schedule.race.date" }}</p>
                </div>

              </ul>
            </div>

        - type: custom-api
          title: Last Race Results
          cache: 1d
          url: https://f1api.dev/api/current/last/race
          template: |
            <div class="flex flex-column gap-5">
              <p class="size-h5">{{ .JSON.String "races.raceName" }}</p>
              <ul class="list collapsible-container" data-collapse-after="5">
                {{ range $i, $v := .JSON.Array "races.results" }}
                <li class="flex items-center {{ if eq $i 0 }}color-primary{{ else if eq $i 1 }}color-highlight{{ end }}">
                  <span class="grow min-width-0">{{ .String "position" }}. {{ .String "driver.shortName" }}</span>
                  <span class="shrink-0 text-right">{{ .String "time" }}</span>
                </li>
                {{ end }}
              </ul>
            </div>

        - type: custom-api
          title: Steam Specials
          cache: 3h
          url: https://store.steampowered.com/api/featuredcategories?cc=id
          template: |
            <ul class="list list-gap-10 collapsible-container" data-collapse-after="5">
            {{ range .JSON.Array "specials.items" }}
            <li>
              <a class="size-h4 color-highlight block text-truncate" href="https://store.steampowered.com/app/{{ .Int "id" }}/">{{ .String "name" }}</a>
              <ul class="list-horizontal-text">
                <li>{{ div (.Int "final_price" | toFloat) 100 | printf "Rp%.2f" }}</li>
                {{ $discount := .Int "discount_percent" }}
              <li{{ if ge $discount 40 }} class="color-positive"{{ end }}>{{ $discount }}% off</li>
              </ul>
            </li>
            {{ end }}
            </ul>

    - size: full
      widgets:
        - type: weather
          hide-header: true
          location: Jakarta, Indonesia
          hide-location: true
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: group
          define: &shared-property
              type: rss
              collapse-after: 8
              style: detailed-list
          cache: 30m
          widgets:
            - title: Market
              feeds:
                - url: https://feeds.bloomberg.com/markets/news.rss
                - url: https://www.ft.com/companies?format=rss
                  title: Financial Times
                  show-thumbnail: true
                - url: https://www.ft.com/markets?format=rss
                  title: Financial Times
                  show-thumbnail: true
              <<: *shared-property
            - title: Tech
              feeds:
                - url: https://www.techpowerup.com/rss/news
                - url: https://www.techpowerup.com/rss/reviews
                - url: https://wccftech.com/topic/hardware/rss
                - url: https://wccftech.com/topic/games/rss
              <<: *shared-property
            - title: F1
              feeds:
                - url: https://www.autosport.com/rss/f1/news/
              <<: *shared-property
              
    - size: small
      widgets:
        - type: clock
          hide-header: true
          hour-format: 24h
          timezones:
            - timezone: Etc/UTC
              label: UTC
            - timezone: America/New_York
              label: EST
            - timezone: America/Los_Angeles
              label: PST
            - timezone: Asia/Tokyo
              label: JST

        - type: markets
          hide-header: true
          cache: 1m
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AMD
              name: AMD
            - symbol: TSM
              name: TSMC

      - type: custom-api
        title: Uptime Kumas
        title-url: $kuma.makuhub.com
        url: $kuma.makuhub.com/api/status-page/$makuhub
        subrequests:
          heartbeats:
            url: $kuma.makuhub.com/api/status-page/heartbeat/$makuhub
        cache: 10m
        template: |
          {{ $hb := .Subrequest "heartbeats" }}

          {{ if not (.JSON.Exists "publicGroupList") }}
          <p class="color-negative">Error reading response</p>
          {{ else if eq (len (.JSON.Array "publicGroupList")) 0 }}
          <p>No monitors found</p>
          {{ else }}

          <ul class="dynamic-columns list-gap-8">
            {{ range .JSON.Array "publicGroupList" }}
            {{ range .Array "monitorList" }}
            {{ $id := .String "id" }}
            {{ $hbArray := $hb.JSON.Array (print "heartbeatList." $id) }}
            <div class="flex items-center gap-12">
              <a class="size-title-dynamic color-highlight text-truncate block grow" href="${UPTIME_KUMA_URL}/dashboard/{{ $id }}"
                target="_blank" rel="noreferrer">
                {{ .String "name" }} </a>
    
              {{ if gt (len $hbArray) 0 }}
                {{ $latest := index $hbArray (sub (len $hbArray) 1) }}
                {{ if eq ($latest.Int "status") 1 }}
                <div>{{ $latest.Int "ping" }}ms</div>
                <div class="monitor-site-status-icon-compact" title="OK">
                  <svg fill="var(--color-positive)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path fill-rule="evenodd"
                      d="M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm3.857-9.809a.75.75 0 0 0-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 1 0-1.06 1.061l2.5 2.5a.75.75 0 0 0 1.137-.089l4-5.5Z"
                      clip-rule="evenodd"></path>
                  </svg>
                </div>
                {{ else }}
                <div><span class="color-negative">DOWN</span></div>
                <div class="monitor-site-status-icon-compact" title="{{ if $latest.Exists "msg" }}{{ $latest.String "msg" }}{{ else
                  }}Error{{ end }}">
                  <svg fill="var(--color-negative)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path fill-rule="evenodd"
                      d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495ZM10 5a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5A.75.75 0 0 1 10 5Zm0 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z"
                      clip-rule="evenodd"></path>
                  </svg>
                </div>
                {{ end }}
              {{ else }}
                <div><span class="color-negative">No data</span></div>
                <div class="monitor-site-status-icon-compact" title="No data available">
                  <svg fill="var(--color-negative)" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                    <path d="M10 18a8 8 0 1 1 0-16 8 8 0 0 1 0 16zm0-2a6 6 0 1 0 0-12 6 6 0 0 0 0 12zm-.75-8a.75.75 0 0 1 1.5 0v3a.75.75 0 0 1-1.5 0V8zm.75 5a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                  </svg>
                </div>
              {{ end }}
            </div>
            {{ end }}
            {{ end }}
          </ul>
          {{ end }}
       
