
- name: Market
  head-widgets:
      - type: markets
        hide-header: true
        markets:
          - symbol: ^JKSE
            name: IHSG
          - symbol: IDR=X
            name: IDR/USD
          - symbol: JPYIDR=X
            name: JPY/IDR  
          - symbol: SGDIDR=X
            name: SGD/IDR
          - symbol: GC=F
            name: GOLD^JKSE
            
  columns:
    - size: full
      widgets:
        - type: rss
          title: News
          style: detailed-list
          collapse-after: 10
          cache: 5m
          feeds:
            - url: https://feeds.bloomberg.com/markets/news.rss
              title: Bloomberg
              limit: 20
            - url: https://www.ft.com/companies?format=rss
              title: Financial Times
              show-thumbnail: true
              limti:  20
            - url: https://www.ft.com/markets?format=rss
              title: Financial Times
              show-thumbnail: true
              limit: 20

    - size: small
      widgets:
        - type: markets
          hide-header: true
          cache: 5m
          markets:
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: SPY
              name: S&P 500
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: TSM
              name: TSMC
            - symbol: GOOG
              name: Google
            - symbol: META
              name: Meta
            - symbol: TSLA
              name: Tesla Motors
