
- name: Market
  head-widgets:
      - type: markets
        hide-header: true
        cache: 1m
        markets:
          - symbol: ^JKSE
            name: IHSG
          - symbol: IDR=X
            name: IDR/USD
          - symbol: JPYIDR=X
            name: JPY/IDR  
          - symbol: SGDIDR=X
            name: SGD/IDR
          - symbol: GC=F
            name: GOLD^JKSE
            
  columns:
    - size: small
      widgets:
        - type: markets
          hide-header: true
          cache: 1m
          sort-by: change
          markets:
          - symbol: BTC-USD
            name: Bitcoin
            chart-link: https://www.tradingview.com/chart/?symbol=btc-usd
          - symbol: SPY
            name: S&P 500
            chart-link: https://www.tradingview.com/chart/?symbol=spy
          - symbol: NVDA
            name: NVIDIA
            chart-link: https://www.tradingview.com/chart/?symbol=nvda
          - symbol: AMD
            name: AMD
            chart-link: https://www.tradingview.com/chart/?symbol=amd
          - symbol: TSM
            name: TSMC
            chart-link: https://www.tradingview.com/chart/?symbol=tsm
          - symbol: GOOG
            name: Google
            chart-link: https://www.tradingview.com/chart/?symbol=goog
          - symbol: INTC
            name: Intel
            chart-link: https://www.tradingview.com/chart/?symbol=intc

    - size: full
      widgets:
       - type: group
         widgets:
         - type: rss
           hide-header: true
           title: Financial Times
           style: detailed-list
           collapse-after: 8
           cache: 5m
           feeds:
              - url: https://www.ft.com/companies?format=rss
                title: Financial Times
                show-thumbnail: false
                limit:  20
              - url: https://www.ft.com/markets?format=rss
                title: Financial Times
                show-thumbnail: false
                limit: 20
         - type: rss
           hide-header: true
           title: Bloomberg
           style: detailed-list
           collapse-after: 8
           cache: 5m
           feeds:
              - url: https://feeds.bloomberg.com/markets/news.rss
                title: Bloomberg
                show-thumbnail: false
                limit: 20              
