
- name: Market
  head-widgets:
      - type: markets
        hide-header: true
        cache: 1m
        markets:
          - symbol: ^JKSE
            name: IHSG
          - symbol: IDR=X
            name: IDR/USD
          - symbol: JPYIDR=X
            name: JPY/IDR  
          - symbol: SGDIDR=X
            name: SGD/IDR
          - symbol: GC=F
            name: GOLD^JKSE
            
  columns:
    - size: small
      widgets:
        - type: markets
          hide-header: true
          cache: 1m
          markets:
          - symbol: BTC-USD
            name: Bitcoin
          - symbol: SPY
            name: S&P 500
          - symbol: NVDA
            name: NVIDIA
          - symbol: AMD
            name: AMD
          - symbol: TSM
            name: TSMC
          - symbol: GOOG
            name: Google
          - symbol: SOFI
            name: SOFI
          - symbol: OPEN
            name: Opendoor
          - symbol: MRVL
            name: Marvell
          - symbol: PLTR
            name: Palantir
          - symbol: AVGO
            name: Broadcomm
          - symbol: ORCL
            name: Oracle
          - symbol: BABA
            name: Alibaba
          - symbol: INTC
            name: Intel

    - size: full
      widgets:
       - type: rss
         title: News
         style: detailed-list
         collapse-after: 10
         cache: 5m
         feeds:
            - url: https://feeds.bloomberg.com/markets/news.rss
              title: Bloomberg
              limit: 20
            - url: https://www.ft.com/companies?format=rss
              title: Financial Times
              show-thumbnail: true
              limti:  20
            - url: https://www.ft.com/markets?format=rss
              title: Financial Times
              show-thumbnail: true
              limit: 20
              
