
- name: Tech & Games
  columns:
    - size: small
      widgets:
        - type: custom-api
          title: Steam Specials
          cache: 30m
          url: https://store.steampowered.com/api/featuredcategories?cc=id
          template: |
            <ul class="list list-gap-20 collapsible-container" data-collapse-after="20">
            {{ range .JSON.Array "specials.items" }}
            <li>
              <a class="size-h4 color-highlight block text-truncate" href="https://store.steampowered.com/app/{{ .Int "id" }}/">{{ .String "name" }}</a>
              <ul class="list-horizontal-text">
                <li>{{ div (.Int "final_price" | toFloat) 100 | printf "Rp%.2f" }}</li>
                {{ $discount := .Int "discount_percent" }}
              <li{{ if ge $discount 40 }} class="color-positive"{{ end }}>{{ $discount }}% off</li>
              </ul>
            </li>
            {{ end }}
            </ul>
        - type: custom-api
          title: Epic Games
          cache: 1h
          url: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en&country=ID&allowCountries=ID
          template: |
            <div>
              {{ if eq .Response.StatusCode 200 }}
                <div class="horizontal-cards-2">
                  {{ range .JSON.Array "data.Catalog.searchStore.elements" }}
                    {{ $price := .String "price.totalPrice.discountPrice" }}
                    {{ $hasPromo := gt (len (.Array "promotions.promotionalOffers")) 0 }}
                    {{ if and $hasPromo (eq $price "0") }}
                      <a href="https://store.epicgames.com/en-US/p/{{ .String "productSlug" }}" target="_blank" class="card">
                        {{ $title := .String "title" }}
                        {{ range .Array "keyImages" }}
                          {{ if eq (.String "type") "OfferImageWide" }}
                            <img src="{{ .String "url" }}" alt="{{ $title }}" style="width: 100%; max-width: 300px; height: 150px; object-fit: cover; border-radius: var(--border-radius);">
                          {{ end }}
                        {{ end }}
                        <div class="card-content">
                          <span class="size-base color-primary">{{ $title }}</span><br>
                          <span class="size-h5 color-subdue">
                            {{ if $hasPromo }}
                              {{ $promotions := .Array "promotions.promotionalOffers" }}
                              {{ if gt (len $promotions) 0 }}
                                {{ $firstPromo := index $promotions 0 }}
                                {{ $offers := $firstPromo.Array "promotionalOffers" }}
                                {{ if gt (len $offers) 0 }}
                                  {{ $firstOffer := index $offers 0 }}
                                  Free until {{ slice ($firstOffer.String "endDate") 0 10 }}
                                {{ else }}
                                  Free this week!
                                {{ end }}
                              {{ else }}
                                Free this week!
                              {{ end }}
                            {{ end }}
                          </span>
                        </div>
                      </a>
                    {{ end }}
                  {{ end }}
                </div>
              {{ else }}
                <p class="color-negative">Error fetching Epic Games data.</p>
              {{ end }}
            </div>

    - size: full
      widgets:
        - type: group
          define: &shared-property
              type: rss
              collapse-after: 8
              style: detailed-list
          cache: 30m
          widgets:
            - title: WccfTech
              feeds:
                - url: https://wccftech.com/topic/hardware/rss
                - url: https://wccftech.com/topic/games/rss
              <<: *shared-property
            - title: TechPowerUp
              feeds:
                - url: https://www.techpowerup.com/rss/news
              <<: *shared-property
            - title: Videocardz
              feeds:
                - url: https://news.google.com/rss/search?q=site%3Avideocardz.com&hl=en-ID&gl=ID&ceid=ID%3Aen
              <<: *shared-property

    - size: full
      widgets:
        - type: group
          define: &shared-properties
              type: reddit
              show-thumbnails: true
              collapse-after: 10
          cache: 1h
          widgets:
          - subreddit: gamingnews
            <<: *shared-properties
          - subreddit: games
            <<: *shared-properties
          - subreddit: pcgaming
            <<: *shared-properties
