
- name: Tech & Games
  columns:
    - size: small
      widgets:
        - type: custom-api
          title: Steam Specials
          cache: 30m
          url: https://store.steampowered.com/api/featuredcategories?cc=id
          template: |
            <ul class="list list-gap-20 collapsible-container" data-collapse-after="20">
            {{ range .JSON.Array "specials.items" }}
            <li>
              <a class="size-h4 color-highlight block text-truncate" href="https://store.steampowered.com/app/{{ .Int "id" }}/">{{ .String "name" }}</a>
              <ul class="list-horizontal-text">
                <li>{{ div (.Int "final_price" | toFloat) 100 | printf "Rp%.2f" }}</li>
                {{ $discount := .Int "discount_percent" }}
              <li{{ if ge $discount 40 }} class="color-positive"{{ end }}>{{ $discount }}% off</li>
              </ul>
            </li>
            {{ end }}
            </ul>

    - size: full
      widgets:
        - type: group
          define: &shared-property
              type: rss
              collapse-after: 8
              style: detailed-list
          cache: 30m
          widgets:
            - title: Videocardz
              feeds:
                - url: https://news.google.com/rss/search?q=site%3Avideocardz.com&hl=en-ID&gl=ID&ceid=ID%3Aen
              <<: *shared-property
            - title: TechPowerUp
              feeds:
                - url: https://www.techpowerup.com/rss/news
              <<: *shared-property
            - title: WccfTech
              feeds:
                - url: https://wccftech.com/topic/hardware/rss
                - url: https://wccftech.com/topic/games/rss
              <<: *shared-property 
              
    - size: full
      widgets:
        - type: group
          define: &shared-properties
              type: reddit
              show-thumbnails: true
              collapse-after: 10
          cache: 1h
          widgets:
          - subreddit: gamingnews
            <<: *shared-properties
          - subreddit: games
            <<: *shared-properties
          - subreddit: pcgaming
            <<: *shared-properties
